config/routes.rb
Rails.application.routes.draw do
  resources :users, only:[:new, :show, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "signup", to: "users#new", as:"signup"
  get "login", to: "login#new", as: "login"
  get "logout", to: "login#destroy", as:"logout"

  post "login", to:"login#create", as: "signin"
  get "dashboard",to:"users#show", as: "dashboard"

  root to:"login#new"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    
    validates :name, :email, :password, presence:true
    validates :email, uniqueness:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def require_login
        if(!session[:user_id])
            redirect_to root_path
          end
    end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
   
   def new
    if(session[:user_id])
        redirect_to controller: "users", action: "show", id: session[:user_id]
    end
   end

   def create
    user  = User.find_by_email(params[:email])
    if(user && user.authenticate(params[:password]))
        session[:user_id] = user.id
        redirect_to controller: "users", action:"show", id:user.id
    else
        redirect_to root_path
    end
   end

   def destroy
    reset_session
    #or session[user_id] = nil
    redirect_to root_path
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user,:require_login, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json


  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to "/login"}
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.permit(:name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Login</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/login/dashboard.html.erb
<h1><%= @user.name%></h1>
<h1><%= @user.email%></h1>
<button><a href="/logout">Logout</a></button>

app/views/login/index.html.erb
<h1>Login</h1>
<%= form_tag("/login", method: "post") do %>

  <%= label_tag(:email,"Enter email")%><br>
  <%= email_field_tag(:email) %><br>

  <%= label_tag(:name,"Enter Password")%><br>
  <%= password_field_tag(:password) %><br>


  <%= submit_tag("Log In") %>
<% end %>
<h6>New User <a href="/signup">click Here</a> </h6>

app/views/login/new.html.erb
<h1>Login</h1>
<%= form_tag login_path do %>

  <%= label_tag(:email,"Enter email")%><br>
  <%= email_field_tag(:email) %><br>

  <%= label_tag(:name,"Enter Password")%><br>
  <%= password_field_tag(:password) %><br>


  <%= submit_tag("Log In") %>
<% end %>
<h6>New User <a href="/signup">click Here</a> </h6>

app/views/login/signup.html.erb
<h1>SignUp</h1>
<%= form_tag("/signup", method: "post") do %>
  <%= label_tag(:name,"Enter name")%><br>
  <%= text_field_tag(:name) %><br>

  <%= label_tag(:name,"Enter Password")%><br>
  <%= password_field_tag(:password) %><br>

  <%= label_tag(:name,"Enter email")%><br>
  <%= email_field_tag(:email) %><br>

  <%= submit_tag("Sign Up") %>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password_digest %>
    <%= form.text_field :password_digest %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_tag users_path, :id=>@user do %>
  <%= label_tag(:name,"Enter name")%><br>
  <%= text_field_tag(:name) %><br>


  <%= label_tag(:name,"Enter email")%><br>
  <%= email_field_tag(:email) %><br>

  <%= label_tag(:name,"Enter Password")%><br>
  <%= password_field_tag(:password) %><br>


  <%= submit_tag("Sign Up") %>
<% end %>

app/views/users/show.html.erb
<h1>Logged in sucessfully</h1>
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<button><a href="/logout">Sign Out</a></button>